log:
  level: debug
  disable_sentry: true

db:
  url: postgres://assistant:assistant@assistant_db:5432/assistant?sslmode=disable
  max_open_connection: 50
  max_idle_connections: 50

listener:
  addr: :8000

email:
  address: example@mail.com
  password: password
