// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "8858efd9569047b2ae89151e6cf79aa7"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"be09b2fcf0da1994404aed7b30725793": "1f8b08000000000000ffbc94c18e13310c86ef790a1fb7829516285c7ae51538579ec4ed5acd38c171287d7b34437766324b454188dbe8ff13cbff674f1e1fe14dcf474523f8929df34ac3a76117096a212df0e0003840c7c742ca18212bf7a81738d1052419488df1ad0338b01613ec09bea1fa67d487edd3a63911f13707a8478e93fbfee3760355f86ba5e654c652ce49037417236c2c4b2792a9c0a7edc66d76ab54e7a4a7fb430534da1743b5f173f220d0016b34f05595c4f6833b5d38b0707986172da7c2c6696eecddd32ab867bbccb9d766ea33caec7f58f9c39cf64d1aa5032989a7f232440ef39dd74c3a8c289eeec7f233b59f7bdafeeb964c510afa11db1f4debde3951f1ca79ac6ff4dd9a3ad8a72a062cadecd1e898f4f6a4587cac81a04b29124ae35d19b754a6361778a6610c809240a04846e0b1780c3428358f19afca6b76c784f13faff8dfe0fc25915b209a4d593e5b9fd3599c0b9af2f2d9da2d95e1976f846be5465b2c5ca30f3077cefd080000ffff368c84382a050000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("001_initial.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "be09b2fcf0da1994404aed7b30725793"})
	}()
	return nil
}()
