// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "8858efd9569047b2ae89151e6cf79aa7"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"be09b2fcf0da1994404aed7b30725793": "1f8b08000000000000ffbc94418fd3301085effe1573dc0a565aa070e995bfc0b99ad8d3eea8ced88cc794fe7b94d24de22c1501216ed17bb633ef7b961f1fe14dcf474523f8929df34ac3a76117096a212df0e0003840c7c742ca18212bf7a81738d1052419488df1ad0338b01613ec09bea1fa67d487edd3a65911f1370ba8478ea3fbfee3760355f86ba56655c652ce49037417236c2c4b2792f1804fdb8ddbec16a9ce494feb430534da1743b5ebe7e841a003d668e0ab2a89ed0777dc7060e1f20c2f5a4e858dd334d8bba74570cf7699722fcdd46794c9ffb0f0879ef64d1aa5032989a7f252228769cf6b261d46144febb1fc4ceda799b6ff7a24539482fe8aed8fda5adb1315af9cafe71b7db7e61cec5315039656f668744c7abf29161f6b20e8528a84d27837c62d9571cc199eb18c0150120814c9083c168f8106a5e66bc69bf29add3161fccf57fc6f70fe92c83d10e3546b89cc9fb6cfe92cce054d79feb4ede6caf02c34c2edef8d36bb948d3e00df39f7230000ffff644c6a0b4e050000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("001_initial.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "be09b2fcf0da1994404aed7b30725793"})
	}()
	return nil
}()
