// +build !skippackr
// Code generated by github.com/gobuffalo/packr/v2. DO NOT EDIT.

// You can use the "packr2 clean" command to clean up this,
// and any other packr generated files.
package packrd

import (
	"github.com/gobuffalo/packr/v2"
	"github.com/gobuffalo/packr/v2/file/resolver"
)

var _ = func() error {
	const gk = "8858efd9569047b2ae89151e6cf79aa7"
	g := packr.New(gk, "")
	hgr, err := resolver.NewHexGzip(map[string]string{
		"be09b2fcf0da1994404aed7b30725793": "1f8b08000000000000ffbc944f8fd33010c5effe1473dc0a565aa070e995afc0b99ad8d3eea8ced88cc7947e7b94d04de25440f9236ed17bb633eff72c3f3ec2ab9e8f8a46f0293be795864fc32e12d4425ae0c10170808e8f8594314256ee512f70a20b4832901ae36b0770602d26d8137c41f5cfa80fdba74db322e22f16508f1c27f7edfbed06aaf0e74acdaa8ca59c9306e82e46d858964e24d3011fb61bb7d9ad529d939eee0f15d0685f0cd5c6cfc9834007acd1c0575512db0feeb4e1c0c2e5195eb49c0a1ba779b0374fabe09eed32e75e9ba9cf28b3ff6ee50f3ded9b344a0752124fe5a5440ef39e5b261d46144ff763f99edacf336dfff548a62805fd88edb7dabab7272a5e398fe71b7db5e61cec5315039656f668744cfae3a6587cac81a04b29124ae35d19b754a6311778a63206404920502423f0583c061a949ac78c57e596dd3161fccf57fc4f70fe9cc85f2359be6d1fd3599c0b9af2f26ddb2d95e15d6884eb4f1b6d712b1b7d20be73ee5b000000ffff6c3db1dd4f050000",
	})
	if err != nil {
		panic(err)
	}
	g.DefaultResolver = hgr

	func() {
		b := packr.New("migrations", "./migrations")
		b.SetResolver("001_initial.sql", packr.Pointer{ForwardBox: gk, ForwardPath: "be09b2fcf0da1994404aed7b30725793"})
	}()
	return nil
}()
